export const images = {
	splashImage: require('../../../assets/images/maison_fondant.png'),
	bg2: require('../../../assets/images/bg2.jpg'),
	trust: require('../../../assets/images/trustit1.png'),
	tustitBg: require('../../../assets/images/trustit-bg.png'),
	tunisia: require('../../../assets/images/tunisia.png'),
	ksa: require('../../../assets/images/ksa.png'),
	fr: require('../../../assets/images/fr.png'),
	usa: require('../../../assets/images/usa.png'),
	backgroung5: require('../../../assets/images/background5.png'),
	backgroung2: require('../../../assets/images/bg4.jpg'),
	profileBg: require('../../../assets/images/profileBackground.png'),
	// onboarding1: require('../../../assets/images/onboarding/snap1.png'),
	// onboarding2: require('../../../assets/images/onboarding/snap2.png'),
	// onboarding3: require('../../../assets/images/onboarding/snap3.png'),
	profilePictureMale: require('../../../assets/images/profilePic.jpg'),
	profilePictureFemale: require('../../../assets/images/female_avatar.jpg'),
	tn: require('../../../assets/images/tunisia.png'),
	done: require('../../../assets/images/done.png'),
	help: require('../../../assets/images/help.png'),
	trust2: require('../../../assets/images/trust2.png'),
	support: require('../../../assets/images/support.png'),
	technique: require('../../../assets/images/technique.png'),
	customer: require('../../../assets/images/customer.png'),
	team: require('../../../assets/images/team.png'),
	trustit_splach: require('../../../assets/images/splashscreen.png'),
	HelpSupport: require('../../../assets/images/helpSupp.png'),
	ChangePassword: require('../../../assets/images/changePassword.png'),
	locationLanguage: require('../../../assets/images/locationLanguage.png'),
	aboutAs: require('../../../assets/images/aboutAss.png'),
	logout: require('../../../assets/images/logout.png'),
	phone: require('../../../assets/images/phone.png'),
	email: require('../../../assets/images/email.png'),
	pay: require('../../../assets/images/logo-pay.jpg'),
	noPhoto: require('../../../assets/images/no_photo.png'),
};
